name: Consolidate Metadata

on:
  workflow_call:

jobs:
  consolidate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd #v4.2.2

      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 #v6.1.0
        with:
          python-version: '3.13'

      - name: Download consolidate_metadata.py script
        run: |
          mkdir scripts
          curl -sSL https://raw.githubusercontent.com/jenkins-infra/plugin-modernizer-tool/main/scripts/consolidate_metadata.py -o scripts/consolidate_metadata.py


      - name: Run consolidation script
        run: python scripts/consolidate_metadata.py

      - name: Commit changes and make PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          BRANCH_NAME="automation/consolidate-metadata"
          git checkout -b "$BRANCH_NAME"
          git add --all ":!scripts"
          git commit -m "Update aggregated metadata for each plugin" || echo "No changes to commit"
          git push origin "$BRANCH_NAME" --force
          gh pr create --title "chore(consolidate): Update aggregated metadata for each plugin" \
             --body "This PR automatically updates aggregated metadata for each plugin." \
             --head "$BRANCH_NAME" \
             --base main || \
          gh pr edit "$BRANCH_NAME" \
           --title "chore(consolidate): Update aggregated metadata for each plugin" \
           --body "This PR automatically updates aggregated metadata for each plugin."
