name: Generate Migration Reports

on:
  workflow_call:

jobs:
  generate-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd #v4.2.2

      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 #v6.1.0
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install pandas

      - name: Download generate_reports.py script
        run: |
          mkdir scripts
          curl -sSL https://raw.githubusercontent.com/jenkins-infra/plugin-modernizer-tool/main/scripts/generate_reports.py -o scripts/generate_reports.py

      - name: Generate report script
        run: python scripts/generate_reports.py

      - name: Commit reports and make PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          BRANCH_NAME="automation/reports"
          git checkout -b "$BRANCH_NAME"
          git add --all ":!scripts"
          git commit -m "Update modernization reports" || echo "No changes to commit"
          git push origin "$BRANCH_NAME" --force
          gh pr create --title "chore(reports): update plugin migration reports" \
             --body "This PR automatically updates the per-plugin failed migrations and summary report based on the latest metadata files." \
             --head "$BRANCH_NAME" \
             --base main || \
          gh pr edit "$BRANCH_NAME" \
           --title "chore(reports): update plugin migration reports" \
           --body "This PR automatically updates the per-plugin failed migrations and summary report based on the latest metadata files."
