name: Validate Metadata

on:
  workflow_call:

jobs:
  validate-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd #v4.2.2

      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 #v6.1.0
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install requests PyGithub jsonschema

      - name: Download validate_metadata.py script
        run: |
          mkdir scripts
          curl -sSL https://raw.githubusercontent.com/jenkins-infra/plugin-modernizer-tool/main/scripts/validate_metadata.py -o scripts/validate_metadata.py

      - name: Validate metadata
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: python scripts/validate_metadata.py